#library "BTSPAWNS"
#include "zcommon.acs"

script "miscfixes_teamspawns" OPEN
{
	if(GetCVar("miscfixes_onetimeteamspawn"))
	{
		ConsoleCommand("sv_useteamstartsindm true");
		Delay(5*35);
		if(GetGameModeState()==GAMESTATE_INPROGRESS)
		{
			ConsoleCommand("sv_useteamstartsindm false");
		}
		while(GetGameModeState()==GAMESTATE_INPROGRESS)
		{
			Delay(1);
		}
		ConsoleCommand("sv_useteamstartsindm true");
	}
}
